### ISSUE TITLE
Dyes/Bleaches changing colors incorrectly

### ISSUE THREAD

**Issue by r-yancey** [skirwan/stylunk#11]
Dyes and Bleaches change colors incorrectly in some cases. For example applying a Lila Bleach to an Albino Maha shirt changes the colors to:
102 153 153
153 153 153
204 102 102
The correct colors in this case should be:
102 153 153
153 153 153
204 **204** **204**

**Comment by skirwan** [comment]
Fixed with 41b90aa8a471eb74fea57b79e4955fdf1d865f1e.  Thanks!
